# Generated by Django 5.0.3 on 2024-03-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_alter_fivecharword_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivecharword',
            name='word',
            field=models.CharField(max_length=5),
        ),
    ]
